import { expect, test } from '@playwright/test'
import { MOCK_FOLDER, openDocumentThroughDialog, watchForErrors } from './harness'

async function openFolder(page: import('@playwright/test').Page, path: string) {
  await page.evaluate((chosen) => window.__fuwaMockVault?.queueDialogSelection([chosen]), path)
  await page.keyboard.press('Meta+o')
}

test('Open Folder shows a sorted Explorer, opens Documents, follows Tabs and restores the Folder', async ({ page }) => {
  const errors = watchForErrors(page)
  await page.goto('/')
  await expect(page.getByTestId('editor-empty-state')).toBeVisible()
  await openFolder(page, MOCK_FOLDER)
  const explorer = page.getByTestId('explorer')
  const rows = explorer.locator('[data-testid^="explorer-row:"]')
  await expect(rows).toHaveText(['Notes', 'Attachments', 'Projects', 'Style catalog', 'Reading list.md', 'Welcome.md'])
  await explorer.getByRole('button', { name: 'Expand Projects' }).click()
  await page.getByTestId(`explorer-row:${MOCK_FOLDER}/Projects/Fuwa.md`).click()
  await expect(page.locator('.bn-editor h1')).toHaveText('Fuwa')
  await expect(page.getByTestId('path-row-crumb')).toHaveText('Notes › Projects › Fuwa.md')
  await explorer.getByRole('button', { name: 'Collapse Projects' }).click()
  await page.getByTestId(`explorer-row:${MOCK_FOLDER}/Welcome.md`).click()
  await expect(page.locator('.bn-editor h1')).toHaveText('Welcome')
  await page.getByTestId(`open-editor:${MOCK_FOLDER}/Projects/Fuwa.md`).click()
  await expect(page.getByTestId(`explorer-row:${MOCK_FOLDER}/Projects/Fuwa.md`).locator('..')).toHaveAttribute('aria-selected', 'true')
  await page.getByTestId(`explorer-row:${MOCK_FOLDER}/Attachments`).click()
  await expect(page.locator('.bn-editor h1')).toHaveText('Fuwa')
  await page.reload()
  await expect(page.getByTestId(`explorer-row:${MOCK_FOLDER}/Projects/Fuwa.md`)).toBeVisible()
  await expect(page.locator('.bn-editor h1')).toHaveText('Fuwa')
  expect(errors.pageErrors).toEqual([])
  expect(errors.consoleErrors).toEqual([])
})

test('switching and closing Folder flushes edits and closes every Tab', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByTestId('editor-empty-state')).toBeVisible()
  await openFolder(page, MOCK_FOLDER)
  await openDocumentThroughDialog(page, `${MOCK_FOLDER}/Welcome.md`)
  await page.locator('.bn-editor p').first().click()
  await page.keyboard.press('End')
  await page.keyboard.type(' Folder switch keeps this edit.')
  await openFolder(page, `${MOCK_FOLDER}/Projects`)
  await expect(page.getByTestId(`explorer-row:${MOCK_FOLDER}/Projects`)).toBeVisible()
  await expect(page.getByTestId('open-editors')).toHaveCount(0)
  const saved = await page.evaluate((path) => window.__fuwaMockVault?.files().find((file) => file.path === path)?.content, `${MOCK_FOLDER}/Welcome.md`)
  expect(saved).toContain('Folder switch keeps this edit.')
  await page.evaluate(() => window.__fuwaTest?.dispatchBrowserMenuCommand?.('file-close-vault'))
  await expect(page.getByRole('tree')).toHaveCount(0)
  const session = await page.evaluate(() => JSON.parse(localStorage.getItem('fuwa:mock-session') ?? '{}'))
  expect(session.folder).toBeNull()
})

test('external changes reload clean Documents, preserve pending edits, and refresh the tree', async ({ page }) => {
  const errors = watchForErrors(page)
  await page.goto('/')
  await expect(page.getByTestId('editor-empty-state')).toBeVisible()
  await openFolder(page, MOCK_FOLDER)
  await openDocumentThroughDialog(page, `${MOCK_FOLDER}/Welcome.md`)
  await page.evaluate((root) => {
    const vault = window.__fuwaMockVault!
    vault.writeNote(`${root}/Welcome.md`, '# Updated externally\n\nClean changes arrive.\n')
    vault.writeNote(`${root}/Added.md`, '# Added\n')
    vault.removeFile(`${root}/Reading list.md`)
    vault.emitExternalChange([`${root}/Welcome.md`, `${root}/Added.md`, `${root}/Reading list.md`])
  }, MOCK_FOLDER)
  await expect(page.locator('.bn-editor h1')).toHaveText('Updated externally')
  await expect(page.getByTestId(`explorer-row:${MOCK_FOLDER}/Added.md`)).toBeVisible()
  await expect(page.getByTestId(`explorer-row:${MOCK_FOLDER}/Reading list.md`)).toHaveCount(0)
  await page.locator('.bn-editor p').first().click()
  await page.keyboard.press('End')
  await page.keyboard.type(' Pending local edit.')
  await page.evaluate((root) => {
    const vault = window.__fuwaMockVault!
    vault.writeNote(`${root}/Welcome.md`, '# Must not replace pending edits\n')
    vault.emitExternalChange([`${root}/Welcome.md`])
  }, MOCK_FOLDER)
  await expect(page.locator('.bn-editor')).toContainText('Pending local edit.')
  await page.keyboard.press('Meta+s')
  await expect.poll(() => page.evaluate((root) => window.__fuwaMockVault?.files().find((file) => file.path === `${root}/Welcome.md`)?.content, MOCK_FOLDER)).toContain('Pending local edit.')
  expect(errors.pageErrors).toEqual([])
  expect(errors.consoleErrors).toEqual([])
})

test('outside Documents show their dimmed parent, stay out of Explorer, and reload externally', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByTestId('editor-empty-state')).toBeVisible()
  await openFolder(page, `${MOCK_FOLDER}/Projects`)
  await openDocumentThroughDialog(page, `${MOCK_FOLDER}/Welcome.md`)
  await expect(page.getByTestId('path-row-crumb')).toHaveText('Notes › Welcome.md')
  await expect(page.getByTestId(`open-editor:${MOCK_FOLDER}/Welcome.md`).getByTestId('open-editor-parent')).toHaveText('Notes')
  await expect(page.getByTestId(`explorer-row:${MOCK_FOLDER}/Welcome.md`)).toHaveCount(0)
  await page.evaluate((path) => {
    window.__fuwaMockVault?.writeNote(path, '# Outside changed\n')
    window.__fuwaMockVault?.emitExternalChange([path])
  }, `${MOCK_FOLDER}/Welcome.md`)
  await expect(page.locator('.bn-editor h1')).toHaveText('Outside changed')
})
